### ISSUE TITLE
Need reverse relations

### ISSUE THREAD

**Issue by jleonard-r7** [benedekfazekas/morpheus#5]
How difficult would it be to mod this tool to reverse the directions of the edges (preferably in clickable svg format as is current). I would like to see semantically, "called by" rather than "calls" relations. I imagine it wouldn't be too hard to get this but a bit of input from the author on how best to go about doing it would save me a lot of time figuring it out. Thanks!

**Comment by benedekfazekas** [comment]
hi @jleonard-r7 I think i was working on this the last time i looked at morpheus -- which was quite a bit ago... check out `var-usages-graph` pls and let me know what you think. I do have some uncommited changes as well somewhere if i remember right.

**Comment by benedekfazekas** [comment]
haha sorry, forgot to mention it was a **branch**

**Comment by jleonard-r7** [comment]
Ah yes. That makes sense. 😃
